### ISSUE TITLE
main_pic not built for FreeBSD but mcmain_pic.vgtest doesn't declare a FreeBSD dependency

### ISSUE THREAD

**Issue by nbriggs** [paulfloyd/freebsd_valgrind#99]
gdbserver_tests/Makefile.am is set up with
```
if !VGCONF_OS_IS_FREEBSD
  check_PROGRAMS += main_pic

  main_pic_LDFLAGS = @FLAG_PIE@
  main_pic_CFLAGS = $(AM_CFLAGS) -fPIC
endif
```
so main_pic doesn't get built on FreeBSD systems, however the mcmain_pic.vgtest:
```
prereq: test -e gdb.pic && if ../tests/arch_test mips32 || ../tests/arch_test mips64 ; then  echo "set heuristic-fence-post 999999"  ; else  echo '' ; fi > mcmain_pic.heur
prog: main_pic
```
doesn't have FreeBSD as a prerequisite, so this test always fails due to the missing program.

**Comment by paulfloyd** [comment]
Curious. I wonder why it was excluded from compilation. I had already seen that there is an issue with setting a breakpoint. The GDB script tries to do that and then a 'continue'. Instead of breaking, Valgrind runs to termination. The remaining GDB script commands then fail.

No problem running standalone.

**Comment by paulfloyd** [comment]
Disabled running the test with
commit 1318708cb186162d4ee933512f7a13f53b973c54
